- hosts: all
  tasks:
    - name: include playbooks
      include_tasks: "tasks/{{ item }}"
      with_items:
        - dotfiles.yml
        - dotfiles_osx.yml
        - download_scripts.yml
        - install_peco.yml
