- name: copy dotfiles
  copy:
    src: "../files/{{ item }}"
    dest: "~/{{ item }}"
  with_items:
    - ".aliases"
    - ".zshrc"
    - ".zlogin"
    - ".zlogout"
    - ".gitconfig"
    - ".config/git/ignore"
    - ".vimrc"
    - ".tmux.conf"
