- hosts: all
  tasks:
    - name: copy dotfiles
      copy:
        src: "../files/{{ item }}"
        dest: "~/{{ item }}"
      with_items:
        - ".aliases"
        - ".gitconfig"
        - ".gitignore.global"
        - ".vimrc"
        - ".tmux.conf"
